title: CodeLabora 
description: CodeLabora es una comunidad open source que busca poner en contacto a jóvenes con proyectos a nivel mundial 
show_downloads: false 
google_analytics:
theme: jekyll-theme-cayman
